name: scim
description: A new Flutter project.
# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.0.11
  url_launcher: ^6.0.18
  flutter_custom_cards: ^0.2.1
  font_awesome_flutter: ^9.2.0
  #flutter_calendar_carousel: ^1.5.3
  back_button_interceptor: ^5.0.2
  carousel_slider: ^3.0.0
  camera: ^0.9.4+16 #support taking camera lib
  path_provider: ^2.0.9
  path: ^1.8.0
  table_calendar: ^3.0.0 #safety calendar
  syncfusion_flutter_calendar: ^19.4.55
  flutter_map: ^0.14.0
  #google_maps_flutter: ^2.1.1
  #widget_marker_google_map: ^0.0.1+1
  latlong2: ^0.8.0 #map option
  intl: ^0.17.0
  http: ^0.13.3 #networking
  #dio #networking
  flutter_bloc: ^8.0.1
  formz: ^0.4.0
  equatable: ^2.0.0
  smart_select: ^4.3.2
  geolocator: ^8.2.0
  #flutter_local_notifications: ^9.4.0
  cached_network_image: ^2.5.1
  gallery_saver: ^2.3.2
  image_picker: ^0.8.4+11
  stream_transform: ^2.0.0
  bloc_concurrency: ^0.2.0
  pull_to_refresh: ^2.0.0
  device_info_plus: ^3.2.2
  #flutter_native_timezone: ^2.0.0
  device_info: ^2.0.3
  localstorage: ^4.0.0+1
  #google_fonts: ^2.3.0\
  firebase_core: ^1.14.1
  firebase_messaging: ^11.2.13
  flutter_local_notifications: ^8.2.0
  flutter_launcher_icons: ^0.9.1
  google_maps_flutter: ^2.1.4
  signalr_client: ^0.1.6
  logging: ^0.11.3+2

flutter_icons:
  image_path: "assets/playstore_image/Icon-App-20x20@1x.png"
  android: true
  ios: true
  #remove_alpha_ios: true


dev_dependencies:
  flutter_test:
    sdk: flutter
#  bloc_test: ^9.0.2
#  mocktail: ^0.2.0

  flutter_lints: ^1.0.0
  #change_app_package_name: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true


  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/Icon/
    - assets/images/other/
    - assets/images/help/
    - assets/fonts/
    - assets/playstore_image/

  fonts:
    - family: NanumBarunGothicLight
      fonts:
        - asset: assets/fonts/NanumBarunGothicLight.ttf
